### ISSUE TITLE
EPIC: Post-winter tree maintenance at Hogsback

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/nccprojects#1]
Several activities involved in the post-winter tree maintenance at Hogsback site.

- [ ] Assess the damage, annotate & inventory what needs replacement.
- [ ] Repair small bite damage with artificial bark.  
- [ ] For dangling branches and severely damaged branches, prune them off.
- [ ] For trees that are fully ringed, determine if grafting can save them, if not, mark for replacement.
- [ ] Tree guards and mats arrived in January, apply both where they are missing.
- [ ] We were short on mulch during the fall planting, mulch the trees more adequately with another load of wood chips.
